language: python
python: 3.9

env:
- PYENV_ROOT="$HOME/.pyenv"

install: |
  if [[ ! -d "$PYENV_ROOT/versions" ]]; then
    rmdir "$PYENV_ROOT"
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  fi
  export PATH="$PYENV_ROOT/bin:$PATH"
  pyenv update
  git clone https://github.com/momo-lab/xxenv-latest.git "$(pyenv root)/plugins/xxenv-latest"
  for v in {5..9}; do pyenv latest install -s 3.$v; pyenv latest uninstall -f 3.$v; done
  pyenv latest local 3.{9,{5..8}}
  pip install --upgrade pip
  pip install poetry tox


cache:
- $PYENV_ROOT
- $HOME/build/applandinc/appmap-python/.tox/

script:
- export PATH="$HOME/.pyenv/bin:$PATH"
- eval "$(pyenv init -)"
- eval "$(pyenv virtualenv-init -)"
- tox -e py39 pylint appmap || travis_terminate 1
- tox
