language: python
python: '3.9'

stages:
- lint
- test
- deploy
cache:
  pip: true
  
install:
- pip install --upgrade pip
- pip install poetry
- poetry install

jobs:
  include:
  - stage: lint
    script:
    - poetry run pylint appmap
    
  - stage: test
    script:
    - poetry run pytest

  - stage: deploy
    script: skip
    # Note publishing this way requires the PyPI credentials to be
    # present in the environment. Travis doesn't currently support
    # providing environment variables to deploy providers through
    # the build config (i.e. in this file). So, they must be
    # provided through the build settings instead.
    deploy:
      provider: script
      script: poetry publish --build
      on:
        tags: true
